// Generated by HEXA self-host compiler
#include "runtime.c"

HexaVal next_rand(HexaVal max);
HexaVal lr_at(HexaVal step);
HexaVal sample_batch(HexaVal corpus, HexaVal n_corpus);
HexaVal eval_ppl(HexaVal weights, HexaVal cfg, HexaVal eval_acts, HexaVal corpus, HexaVal n_corpus);
HexaVal kr_acc(HexaVal weights, HexaVal cfg, HexaVal eval_acts);
HexaVal measure_phi_proxy(HexaVal eval_acts, HexaVal cfg);
HexaVal r2_upload(HexaVal local_path, HexaVal step);

HexaVal D;
HexaVal FF;
HexaVal NL;
HexaVal VOCAB;
HexaVal SEQ;
HexaVal RANK;
HexaVal BATCH;
HexaVal GRAD_ACC;
HexaVal STEPS;
HexaVal EVAL_EVERY;
HexaVal SAVE_EVERY;
HexaVal LOG_EVERY;
HexaVal LR_MAX;
HexaVal LR_MIN;
HexaVal WARMUP;
HexaVal EPS;
HexaVal INIT_SCALE;
HexaVal SEED;
HexaVal CKPT_DIR;
HexaVal R2_PREFIX;
HexaVal MODEL_TAG;
HexaVal ROUND;
HexaVal CORPUS_PATH;
HexaVal HELDOUT_LEN;
HexaVal KR_PERIOD;
HexaVal RNG;
HexaVal cuda_rc;
HexaVal _;
HexaVal kernels_rc;
HexaVal math_rc;
HexaVal cfg;
HexaVal corpus;
HexaVal n_corpus;
HexaVal weights;
HexaVal acts;
HexaVal grad;
HexaVal eval_acts;
HexaVal _;
HexaVal _mkdir;
HexaVal t0;
HexaVal step;
HexaVal last_loss;
HexaVal first_loss;
HexaVal eval_loss_1;
HexaVal eval_loss_2;
HexaVal eval_loss_3;
HexaVal best_eval_loss;
HexaVal best_eval_step;
HexaVal early_stopped;
HexaVal t1;
HexaVal total_s;
HexaVal final_path;
HexaVal final_rc;
HexaVal _;

static HexaIC __hexa_ic_0 = {0};
static HexaIC __hexa_ic_1 = {0};
static HexaIC __hexa_ic_2 = {0};
static HexaIC __hexa_ic_3 = {0};
static HexaIC __hexa_ic_4 = {0};
static HexaIC __hexa_ic_5 = {0};
static HexaIC __hexa_ic_6 = {0};
static HexaIC __hexa_ic_7 = {0};
static HexaIC __hexa_ic_8 = {0};
static HexaIC __hexa_ic_9 = {0};

HexaVal next_rand(HexaVal max) {
    RNG = hexa_mod(hexa_add(hexa_mul(RNG, hexa_int(1103515245)), hexa_int(12345)), hexa_int(2147483647));
    HexaVal m = hexa_mod(RNG, max);
    if (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(m); HexaVal __r=(hexa_int(0)); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) < (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i < __r.i); })))) {
        return hexa_sub(hexa_int(0), m);
    }
    return m;
    return hexa_void();
}


HexaVal lr_at(HexaVal step) {
    if (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(step); HexaVal __r=(WARMUP); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) <= (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i <= __r.i); })))) {
        return hexa_div(hexa_mul(LR_MAX, hexa_mul(step, hexa_float(1.0))), hexa_mul(WARMUP, hexa_float(1.0)));
    }
    HexaVal t = hexa_div(hexa_mul(hexa_sub(step, WARMUP), hexa_float(1.0)), hexa_mul(hexa_sub(STEPS, WARMUP), hexa_float(1.0)));
    HexaVal pi = hexa_float(3.14159265358979);
    return hexa_add(LR_MIN, hexa_mul(hexa_mul(hexa_float(0.5), hexa_sub(LR_MAX, LR_MIN)), hexa_add(hexa_float(1.0), hexa_float(cos(__hx_to_double(hexa_mul(pi, t)))))));
    return hexa_void();
}


HexaVal sample_batch(HexaVal corpus, HexaVal n_corpus) {
    HexaVal max_start = hexa_sub(hexa_sub(n_corpus, SEQ), hexa_int(1));
    if (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(max_start); HexaVal __r=(hexa_int(0)); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) <= (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i <= __r.i); })))) {
        hexa_println(hexa_add(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] FATAL — corpus too short: "), hexa_to_string(n_corpus)), hexa_str(" bytes (need > ")), hexa_to_string(hexa_add(SEQ, hexa_int(1)))), hexa_str(")")));
        return hexa_array_push(hexa_array_push(hexa_array_new(), hexa_ptr_null()), hexa_ptr_null());
    }
    HexaVal tok_flat = hexa_array_new();
    HexaVal tgt_flat = hexa_array_new();
    HexaVal b = hexa_int(0);
    while (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(b); HexaVal __r=(BATCH); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) < (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i < __r.i); })))) {
        HexaVal start = next_rand(max_start);
        HexaVal i = hexa_int(0);
        while (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(i); HexaVal __r=(SEQ); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) < (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i < __r.i); })))) {
            tok_flat = hexa_array_push(tok_flat, hexa_index_get(corpus, hexa_add(start, i)));
            tgt_flat = hexa_array_push(tgt_flat, hexa_index_get(corpus, hexa_add(hexa_add(start, i), hexa_int(1))));
            i = hexa_add(i, hexa_int(1));
        }
        b = hexa_add(b, hexa_int(1));
    }
    HexaVal tok_dev = hexa_call1(int_array_to_gpu, tok_flat);
    HexaVal tgt_dev = hexa_call1(int_array_to_gpu, tgt_flat);
    return hexa_array_push(hexa_array_push(hexa_array_new(), tok_dev), tgt_dev);
    return hexa_void();
}


HexaVal eval_ppl(HexaVal weights, HexaVal cfg, HexaVal eval_acts, HexaVal corpus, HexaVal n_corpus) {
    HexaVal _ = hexa_void();
    HexaVal avail = HELDOUT_LEN;
    HexaVal start = hexa_sub(hexa_sub(n_corpus, avail), hexa_int(1));
    if (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(start); HexaVal __r=(hexa_int(0)); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) < (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i < __r.i); })))) {
        start = hexa_int(0);
    }
    HexaVal rows = hexa_div(HELDOUT_LEN, SEQ);
    if (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(rows); HexaVal __r=(hexa_int(1)); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) < (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i < __r.i); })))) {
        return hexa_float(0.0);
    }
    HexaVal total = hexa_float(0.0);
    HexaVal r = hexa_int(0);
    while (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(r); HexaVal __r=(rows); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) < (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i < __r.i); })))) {
        HexaVal row_start = hexa_add(start, hexa_mul(r, SEQ));
        HexaVal toks = hexa_array_new();
        HexaVal tgts = hexa_array_new();
        HexaVal i = hexa_int(0);
        while (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(i); HexaVal __r=(SEQ); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) < (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i < __r.i); })))) {
            toks = hexa_array_push(toks, hexa_index_get(corpus, hexa_add(row_start, i)));
            tgts = hexa_array_push(tgts, hexa_index_get(corpus, hexa_add(hexa_add(row_start, i), hexa_int(1))));
            i = hexa_add(i, hexa_int(1));
        }
        HexaVal tok_dev = hexa_call1(int_array_to_gpu, toks);
        HexaVal tgt_dev = hexa_call1(int_array_to_gpu, tgts);
        HexaVal logits = hexa_call4(gpu_forward_full, tok_dev, weights, eval_acts, cfg);
        HexaVal loss_buf = hexa_call1(cuda_malloc, hexa_int(4));
        _ = hexa_call2(cuda_memset_zero, loss_buf, hexa_int(4));
        HexaVal dlogits = hexa_call1(cuda_malloc, hexa_mul(hexa_mul(SEQ, VOCAB), hexa_int(4)));
        _ = gpu_ce_loss_grad(logits, tgt_dev, loss_buf, dlogits, SEQ, VOCAB);
        _ = hexa_call0(cudaDeviceSynchronize);
        HexaVal host = hexa_ptr_alloc(hexa_int(4));
        _ = hexa_call3(cuda_memcpy_d2h, host, loss_buf, hexa_int(4));
        HexaVal ce = hexa_ptr_read_f32(host, hexa_int(0));
        hexa_ptr_free(host, hexa_int(0));
        hexa_call1(cuda_free, loss_buf);
        hexa_call1(cuda_free, dlogits);
        hexa_call1(cuda_free, tok_dev);
        hexa_call1(cuda_free, tgt_dev);
        total = hexa_add(total, ce);
        r = hexa_add(r, hexa_int(1));
    }
    return hexa_float(exp(__hx_to_double(hexa_div(total, hexa_mul(rows, hexa_float(1.0))))));
    return hexa_void();
}


HexaVal kr_acc(HexaVal weights, HexaVal cfg, HexaVal eval_acts) {
    return hexa_sub(hexa_int(0), hexa_int(1));
    return hexa_void();
}


HexaVal measure_phi_proxy(HexaVal eval_acts, HexaVal cfg) {
    HexaVal cap_bytes = hexa_mul(hexa_int(1024), hexa_int(1024));
    HexaVal hidden_bytes = hexa_mul(hexa_mul(hexa_map_get_ic(cfg, "SEQ", &__hexa_ic_0), hexa_map_get_ic(cfg, "D", &__hexa_ic_1)), hexa_int(4));
    HexaVal nbytes = (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(hidden_bytes); HexaVal __r=(cap_bytes); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) < (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i < __r.i); }))) ? hidden_bytes : cap_bytes);
    HexaVal n_floats = hexa_div(nbytes, hexa_int(4));
    if (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(n_floats); HexaVal __r=(hexa_int(2)); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) < (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i < __r.i); })))) {
        return hexa_float(0.0);
    }
    HexaVal y_dev = hexa_map_get_ic(hexa_index_get(hexa_map_get_ic(eval_acts, "layers", &__hexa_ic_3), hexa_sub(hexa_map_get_ic(cfg, "NL", &__hexa_ic_2), hexa_int(1))), "y", &__hexa_ic_4);
    HexaVal host = hexa_ptr_alloc(nbytes);
    HexaVal _ = hexa_call3(cuda_memcpy_d2h, host, y_dev, nbytes);
    HexaVal mean = hexa_float(0.0);
    HexaVal i = hexa_int(0);
    while (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(i); HexaVal __r=(n_floats); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) < (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i < __r.i); })))) {
        mean = hexa_add(mean, hexa_ptr_read_f32(host, i));
        i = hexa_add(i, hexa_int(1));
    }
    mean = hexa_div(mean, hexa_mul(n_floats, hexa_float(1.0)));
    HexaVal var_sum = hexa_float(0.0);
    HexaVal j = hexa_int(0);
    while (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(j); HexaVal __r=(n_floats); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) < (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i < __r.i); })))) {
        HexaVal d = hexa_sub(hexa_ptr_read_f32(host, j), mean);
        var_sum = hexa_add(var_sum, hexa_mul(d, d));
        j = hexa_add(j, hexa_int(1));
    }
    hexa_ptr_free(host, hexa_int(0));
    return hexa_div(var_sum, hexa_mul(n_floats, hexa_float(1.0)));
    return hexa_void();
}


HexaVal r2_upload(HexaVal local_path, HexaVal step) {
    HexaVal remote = hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(R2_PREFIX, hexa_str("/r")), hexa_to_string(ROUND)), hexa_str("/step_")), hexa_to_string(step)), hexa_str("/"));
    HexaVal cmd = hexa_add(hexa_add(hexa_add(hexa_str("rclone copy "), local_path), hexa_str(" ")), remote);
    hexa_println(hexa_add(hexa_str("[train_clm_kr] R2 upload: "), cmd));
    HexaVal rc = hexa_exec(cmd);
    if (hexa_truthy(hexa_bool(!hexa_truthy(hexa_eq(rc, hexa_int(0)))))) {
        hexa_println(hexa_add(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] WARN — rclone exit="), hexa_to_string(rc)), hexa_str(" (R2 upload deferred, local ckpt intact: ")), local_path), hexa_str(")")));
    }
    return rc;
    return hexa_void();
}


int main(int argc, char** argv) {
    hexa_set_args(argc, argv);
    /* import: cuda_ffi */
    /* import: cuda_rtc */
    /* import: cuda_kernels */
    /* import: gpu_train */
    /* import: corpus_loader */
    D = hexa_int(512);
    FF = hexa_int(2048);
    NL = hexa_int(12);
    VOCAB = hexa_int(256);
    SEQ = hexa_int(512);
    RANK = hexa_int(64);
    BATCH = hexa_int(1);
    GRAD_ACC = hexa_int(8);
    STEPS = hexa_int(20000);
    EVAL_EVERY = hexa_int(500);
    SAVE_EVERY = hexa_int(2000);
    LOG_EVERY = hexa_int(20);
    LR_MAX = hexa_float(0.0003);
    LR_MIN = hexa_float(0.00003);
    WARMUP = hexa_int(500);
    EPS = hexa_float(0.00001);
    INIT_SCALE = hexa_float(0.02);
    SEED = hexa_int(54321);
    CKPT_DIR = hexa_str("/workspace/ckpt_clm_byte_kr");
    R2_PREFIX = hexa_str("r2:anima-models/clm_byte_kr");
    MODEL_TAG = hexa_str("clm_byte_kr");
    ROUND = hexa_int(1);
    CORPUS_PATH = hexa_str("training/corpus_ko_seed.tok");
    HELDOUT_LEN = hexa_int(4096);
    KR_PERIOD = hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_push(hexa_array_new(), hexa_int(236)), hexa_int(149)), hexa_int(136)), hexa_int(235)), hexa_int(133)), hexa_int(149)), hexa_int(237)), hexa_int(149)), hexa_int(152)), hexa_int(236)), hexa_int(132)), hexa_int(184)), hexa_int(236)), hexa_int(154)), hexa_int(148)), hexa_int(32));
    RNG = SEED;
    hexa_println(hexa_str("[train_clm_kr] =================================================="));
    hexa_println(hexa_str("[train_clm_kr] CLM byte-level KR (GPU, hexa-native, zero-Rust)"));
    hexa_println(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] config: D="), hexa_to_string(D)), hexa_str(" FF=")), hexa_to_string(FF)), hexa_str(" NL=")), hexa_to_string(NL)), hexa_str(" VOCAB=")), hexa_to_string(VOCAB)), hexa_str(" SEQ=")), hexa_to_string(SEQ)), hexa_str(" RANK=")), hexa_to_string(RANK)), hexa_str(" BATCH=")), hexa_to_string(BATCH)), hexa_str(" GRAD_ACC=")), hexa_to_string(GRAD_ACC)), hexa_str(" effective_batch=")), hexa_to_string(hexa_mul(BATCH, GRAD_ACC))));
    hexa_println(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] schedule: STEPS="), hexa_to_string(STEPS)), hexa_str(" WARMUP=")), hexa_to_string(WARMUP)), hexa_str(" LR_MAX=")), hexa_to_string(LR_MAX)), hexa_str(" LR_MIN=")), hexa_to_string(LR_MIN)));
    hexa_println(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] log_every="), hexa_to_string(LOG_EVERY)), hexa_str(" eval_every=")), hexa_to_string(EVAL_EVERY)), hexa_str(" save_every=")), hexa_to_string(SAVE_EVERY)));
    hexa_println(hexa_add(hexa_str("[train_clm_kr] ckpt_dir="), CKPT_DIR));
    hexa_println(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] r2_prefix="), R2_PREFIX), hexa_str(" round=")), hexa_to_string(ROUND)));
    hexa_println(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] random baseline ln("), hexa_to_string(VOCAB)), hexa_str(") = ")), hexa_to_string(hexa_float(log(__hx_to_double(hexa_mul(VOCAB, hexa_float(1.0))))))));
    hexa_println(hexa_str("[train_clm_kr] =================================================="));
    cuda_rc = hexa_call0(cuda_init);
    if (hexa_truthy(hexa_bool(!hexa_truthy(hexa_eq(cuda_rc, hexa_int(0)))))) {
        hexa_println(hexa_add(hexa_str("[train_clm_kr] FATAL — cuda_init failed rc="), hexa_to_string(cuda_rc)));
        hexa_println(hexa_str("[train_clm_kr] check: nvidia-smi, libcudart.so, libcublas.so on LD_LIBRARY_PATH"));
        return hexa_void();
    }
    _ = hexa_call0(cuda_mem_info);
    kernels_rc = hexa_call0(gpu_init_kernels);
    if (hexa_truthy(hexa_bool(!hexa_truthy(hexa_eq(kernels_rc, hexa_int(0)))))) {
        hexa_println(hexa_add(hexa_str("[train_clm_kr] FATAL — gpu_init_kernels failed rc="), hexa_to_string(kernels_rc)));
        hexa_println(hexa_str("[train_clm_kr] check: libnvrtc.so.12, /usr/local/cuda-12.4/include"));
        HexaVal _ = hexa_call0(cuda_shutdown);
        return hexa_void();
    }
    hexa_println(hexa_str("[train_clm_kr] kernels: NVRTC compile OK (12 custom kernels)"));
    math_rc = hexa_call2(cublasSetMathMode, G_CUBLAS_HANDLE, hexa_int(1));
    if (hexa_truthy(hexa_bool(!hexa_truthy(hexa_eq(math_rc, hexa_int(0)))))) {
        hexa_println(hexa_add(hexa_add(hexa_str("[train_clm_kr] WARN — cublasSetMathMode rc="), hexa_to_string(math_rc)), hexa_str(" (tensor cores may not be active)")));
    } else {
        hexa_println(hexa_str("[train_clm_kr] tensor cores: CUBLAS_TENSOR_OP_MATH enabled"));
    }
    cfg = GpuClmConfig(D, FF, NL, VOCAB, SEQ, RANK, EPS, INIT_SCALE);
    hexa_println(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] cfg: D="), hexa_to_string(hexa_map_get_ic(cfg, "D", &__hexa_ic_5))), hexa_str(" FF=")), hexa_to_string(hexa_map_get_ic(cfg, "FF", &__hexa_ic_6))), hexa_str(" NL=")), hexa_to_string(hexa_map_get_ic(cfg, "NL", &__hexa_ic_7))), hexa_str(" SEQ=")), hexa_to_string(hexa_map_get_ic(cfg, "SEQ", &__hexa_ic_8))), hexa_str(" RANK=")), hexa_to_string(hexa_map_get_ic(cfg, "RANK", &__hexa_ic_9))));
    corpus = hexa_call1(load_corpus, CORPUS_PATH);
    n_corpus = hexa_int(hexa_len(corpus));
    if (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(n_corpus); HexaVal __r=(hexa_add(SEQ, hexa_int(2))); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) < (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i < __r.i); })))) {
        hexa_println(hexa_add(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] FATAL — corpus too short: "), hexa_to_string(n_corpus)), hexa_str(" bytes (need >= ")), hexa_to_string(hexa_add(SEQ, hexa_int(2)))), hexa_str(")")));
        HexaVal _ = hexa_call0(cuda_shutdown);
        return hexa_void();
    }
    hexa_println(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] corpus: "), hexa_to_string(n_corpus)), hexa_str(" bytes from ")), CORPUS_PATH));
    hexa_println(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] first bytes: "), hexa_to_string(hexa_index_get(corpus, hexa_int(0)))), hexa_str(" ")), hexa_to_string(hexa_index_get(corpus, hexa_int(1)))), hexa_str(" ")), hexa_to_string(hexa_index_get(corpus, hexa_int(2)))), hexa_str(" ")), hexa_to_string(hexa_index_get(corpus, hexa_int(3)))), hexa_str(" ")), hexa_to_string(hexa_index_get(corpus, hexa_int(4)))), hexa_str(" ...")));
    weights = hexa_call2(init_gpu_weights, cfg, SEED);
    hexa_println(hexa_add(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] weights: GPU initialized (seed="), hexa_to_string(SEED)), hexa_str(", scale=")), hexa_to_string(INIT_SCALE)), hexa_str(")")));
    acts = hexa_call2(alloc_fwd_buffers, cfg, hexa_mul(BATCH, SEQ));
    grad = hexa_call1(alloc_grad_buffers, cfg);
    eval_acts = hexa_call2(alloc_fwd_buffers, cfg, HELDOUT_LEN);
    hexa_println(hexa_str("[train_clm_kr] buffers: fwd/grad/eval allocated on GPU"));
    _ = hexa_call0(cuda_mem_info);
    _mkdir = hexa_exec(hexa_add(hexa_str("mkdir -p "), CKPT_DIR));
    hexa_println(hexa_str("[train_clm_kr] =================================================="));
    hexa_println(hexa_add(hexa_str("[train_clm_kr] training start — STEPS="), hexa_to_string(STEPS)));
    hexa_println(hexa_str("[train_clm_kr] =================================================="));
    t0 = hexa_clock();
    step = hexa_int(1);
    last_loss = hexa_float(0.0);
    first_loss = hexa_float(0.0);
    eval_loss_1 = hexa_sub(hexa_int(0), hexa_float(1.0));
    eval_loss_2 = hexa_sub(hexa_int(0), hexa_float(1.0));
    eval_loss_3 = hexa_sub(hexa_int(0), hexa_float(1.0));
    best_eval_loss = hexa_float(999999.0);
    best_eval_step = hexa_int(0);
    early_stopped = hexa_bool(0);
    while (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(step); HexaVal __r=(STEPS); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) <= (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i <= __r.i); })))) {
        if (hexa_truthy(early_stopped)) {
            break;
        }
        HexaVal _zero = hexa_call2(gpu_zero_grad, grad, cfg);
        HexaVal acc_loss = hexa_float(0.0);
        HexaVal micro = hexa_int(0);
        while (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(micro); HexaVal __r=(GRAD_ACC); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) < (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i < __r.i); })))) {
            HexaVal buffers = sample_batch(corpus, n_corpus);
            HexaVal tok_dev = hexa_index_get(buffers, hexa_int(0));
            HexaVal tgt_dev = hexa_index_get(buffers, hexa_int(1));
            if (hexa_truthy(hexa_eq(hexa_ptr_addr(tok_dev), hexa_int(0)))) {
                hexa_println(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] FATAL — sample_batch returned null at step="), hexa_to_string(step)), hexa_str(" micro=")), hexa_to_string(micro)));
                HexaVal _ = hexa_call0(cuda_shutdown);
                return hexa_void();
            }
            HexaVal logits = hexa_call4(gpu_forward_full, tok_dev, weights, acts, cfg);
            HexaVal raw_loss = gpu_backward_full_with_embed(logits, tgt_dev, tok_dev, acts, weights, grad, cfg);
            acc_loss = hexa_add(acc_loss, raw_loss);
            hexa_call1(cuda_free, tok_dev);
            hexa_call1(cuda_free, tgt_dev);
            micro = hexa_add(micro, hexa_int(1));
        }
        HexaVal loss = hexa_div(acc_loss, hexa_mul(GRAD_ACC, hexa_float(1.0)));
        HexaVal lr = hexa_div(lr_at(step), hexa_mul(GRAD_ACC, hexa_float(1.0)));
        HexaVal _sgd = hexa_call4(gpu_sgd_step, weights, grad, lr, cfg);
        if (hexa_truthy(hexa_eq(step, hexa_int(1)))) {
            first_loss = loss;
        }
        last_loss = loss;
        if (hexa_truthy(hexa_bool(hexa_truthy(hexa_eq(hexa_mod(step, LOG_EVERY), hexa_int(0))) || hexa_truthy(hexa_eq(step, hexa_int(1)))))) {
            HexaVal elapsed = hexa_sub(hexa_clock(), t0);
            hexa_println(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] step="), hexa_to_string(step)), hexa_str(" loss=")), hexa_to_string(loss)), hexa_str(" lr=")), hexa_to_string(lr)), hexa_str(" elapsed=")), hexa_to_string(elapsed)), hexa_str("s")));
        }
        if (hexa_truthy(hexa_eq(hexa_mod(step, EVAL_EVERY), hexa_int(0)))) {
            HexaVal ppl = eval_ppl(weights, cfg, eval_acts, corpus, n_corpus);
            HexaVal hits = kr_acc(weights, cfg, eval_acts);
            hexa_println(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] eval step="), hexa_to_string(step)), hexa_str(" ppl=")), hexa_to_string(ppl)), hexa_str(" kr_acc=")), hexa_to_string(hits)), hexa_str("/16")));
            HexaVal phi_proxy = measure_phi_proxy(eval_acts, cfg);
            hexa_println(hexa_add(hexa_add(hexa_add(hexa_str("[phi] step="), hexa_to_string(step)), hexa_str(" phi_proxy=")), hexa_to_string(phi_proxy)));
            if (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(ppl); HexaVal __r=(best_eval_loss); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) < (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i < __r.i); })))) {
                best_eval_loss = ppl;
                best_eval_step = step;
            }
            eval_loss_1 = eval_loss_2;
            eval_loss_2 = eval_loss_3;
            eval_loss_3 = ppl;
            if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool(hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(eval_loss_1); HexaVal __r=(hexa_float(0.0)); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) > (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i > __r.i); }))) && hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(eval_loss_2); HexaVal __r=(hexa_float(0.0)); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) > (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i > __r.i); }))))) && hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(eval_loss_3); HexaVal __r=(hexa_float(0.0)); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) > (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i > __r.i); })))))) {
                if (hexa_truthy(hexa_bool(hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(eval_loss_2); HexaVal __r=(eval_loss_1); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) > (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i > __r.i); }))) && hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(eval_loss_3); HexaVal __r=(eval_loss_2); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) > (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i > __r.i); })))))) {
                    hexa_println(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_add(hexa_str("[early-stop] eval loss increased 3x consecutive: "), hexa_to_string(eval_loss_1)), hexa_str(", ")), hexa_to_string(eval_loss_2)), hexa_str(", ")), hexa_to_string(eval_loss_3)), hexa_str(". Saving best and stopping.")));
                    HexaVal es_path = hexa_add(hexa_add(hexa_add(CKPT_DIR, hexa_str("/best_step_")), hexa_to_string(best_eval_step)), hexa_str(".hexackpt"));
                    HexaVal es_rc = hexa_call3(save_checkpoint_gpu, weights, cfg, es_path);
                    if (hexa_truthy(hexa_eq(es_rc, hexa_int(0)))) {
                        hexa_println(hexa_add(hexa_str("[early-stop] saved best checkpoint → "), es_path));
                        HexaVal _ = r2_upload(es_path, best_eval_step);
                    } else {
                        hexa_println(hexa_add(hexa_str("[early-stop] WARN — save failed rc="), hexa_to_string(es_rc)));
                    }
                    early_stopped = hexa_bool(1);
                }
            }
        }
        if (hexa_truthy(hexa_eq(hexa_mod(step, SAVE_EVERY), hexa_int(0)))) {
            HexaVal ckpt_path = hexa_add(hexa_add(hexa_add(CKPT_DIR, hexa_str("/step_")), hexa_to_string(step)), hexa_str(".hexackpt"));
            HexaVal save_rc = hexa_call3(save_checkpoint_gpu, weights, cfg, ckpt_path);
            if (hexa_truthy(hexa_eq(save_rc, hexa_int(0)))) {
                hexa_println(hexa_add(hexa_str("[train_clm_kr] saved checkpoint → "), ckpt_path));
                HexaVal _ = r2_upload(ckpt_path, step);
            } else {
                hexa_println(hexa_add(hexa_add(hexa_add(hexa_str("[train_clm_kr] WARN — save_checkpoint_gpu rc="), hexa_to_string(save_rc)), hexa_str(" path=")), ckpt_path));
            }
        }
        step = hexa_add(step, hexa_int(1));
    }
    t1 = hexa_clock();
    total_s = hexa_sub(t1, t0);
    hexa_println(hexa_str(""));
    hexa_println(hexa_str("[train_clm_kr] =================================================="));
    hexa_println(hexa_add(hexa_str("[train_clm_kr] training complete — STEPS="), hexa_to_string(STEPS)));
    hexa_println(hexa_add(hexa_str("[train_clm_kr] loss_initial = "), hexa_to_string(first_loss)));
    hexa_println(hexa_add(hexa_str("[train_clm_kr] loss_final   = "), hexa_to_string(last_loss)));
    hexa_println(hexa_add(hexa_str("[train_clm_kr] Δ loss       = "), hexa_to_string(hexa_sub(last_loss, first_loss))));
    hexa_println(hexa_add(hexa_str("[train_clm_kr] total_s      = "), hexa_to_string(total_s)));
    hexa_println(hexa_add(hexa_str("[train_clm_kr] s/step       = "), hexa_to_string(hexa_div(total_s, hexa_mul(STEPS, hexa_float(1.0))))));
    hexa_println(hexa_str("[train_clm_kr] =================================================="));
    if (hexa_truthy(hexa_bool(__extension__ ({ HexaVal __l=(last_loss); HexaVal __r=(hexa_sub(first_loss, hexa_float(0.1))); (__l.tag==TAG_FLOAT||__r.tag==TAG_FLOAT) ? ((__l.tag==TAG_FLOAT?__l.f:(double)__l.i) < (__r.tag==TAG_FLOAT?__r.f:(double)__r.i)) : (__l.i < __r.i); })))) {
        HexaVal improvement = hexa_div(hexa_mul(hexa_sub(first_loss, last_loss), hexa_float(100.0)), first_loss);
        hexa_println(hexa_add(hexa_add(hexa_str("[train_clm_kr] PASS — relative improvement = "), hexa_to_string(improvement)), hexa_str("%")));
    } else {
        hexa_println(hexa_str("[train_clm_kr] WEAK — loss did not drop materially (need diagnosis)"));
    }
    final_path = hexa_add(CKPT_DIR, hexa_str("/final.hexackpt"));
    final_rc = hexa_call3(save_checkpoint_gpu, weights, cfg, final_path);
    if (hexa_truthy(hexa_eq(final_rc, hexa_int(0)))) {
        hexa_println(hexa_add(hexa_str("[train_clm_kr] saved final checkpoint → "), final_path));
        HexaVal _ = r2_upload(final_path, STEPS);
    } else {
        hexa_println(hexa_add(hexa_str("[train_clm_kr] WARN — final save_checkpoint_gpu rc="), hexa_to_string(final_rc)));
    }
    _ = hexa_call0(cuda_shutdown);
    hexa_println(hexa_str("[train_clm_kr] cuda_shutdown — done. Bye."));
    return 0;
}
