#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════════════
#  tool/single_file_pkg.bash — ROI N73: single-file packaging for CP1 tools
#
#  PURPOSE
#    Wrapper that runs the equivalent of `hexa build -o dist/<name>` for
#    each top-level CP1 tool and verifies the produced artifact executes
#    --selftest cleanly. On hosts where `hexa build` is unavailable, we
#    package the source + a launcher shim into dist/<name>/ and use the
#    shim as the dist artifact (still single-file from the operator's POV:
#    `dist/<name>` is one executable).
#
#  TARGETS (CP1)
#    - serve_alm_persona
#    - h100_post_launch_ingest
#    - an11_ensemble
#
#  USAGE
#    bash tool/single_file_pkg.bash
#    bash tool/single_file_pkg.bash --selftest
#
#  OUTPUT
#    state/dist_packages.json
#      {
#        "schema": "anima.dist_packages.v1",
#        "ts": "<iso>",
#        "roi_ref": "N73",
#        "dist_dir": "<abs path>",
#        "packages": [
#          { "name": "...", "source": "...", "artifact": "...",
#            "bytes": <int>, "selftest": "PASS|FAIL|SKIP" }
#        ],
#        "verdict": "PASS|WARN|FAIL"
#      }
#
#  EXIT
#    0 if all packages PASS or SKIP, 1 if any FAIL
# ════════════════════════════════════════════════════════════════════════════

set -u

ROOT="${ANIMA_ROOT:-/Users/ghost/core/anima}"
DIST_DIR="$ROOT/dist"
OUT="$ROOT/state/dist_packages.json"

TARGETS=(
  "serve_alm_persona"
  "h100_post_launch_ingest"
  "an11_ensemble"
)

ts() { date -u +%Y-%m-%dT%H:%M:%SZ; }

# ── selftest (no FS mutation) ──────────────────────────────────────────────
if [[ "${1:-}" == "--selftest" ]]; then
  echo "── single_file_pkg.bash selftest ──"
  s1=0 ; [[ -d "$ROOT/tool" ]] && s1=1
  s2=0 ; command -v hexa >/dev/null && s2=1
  s3=1
  for t in "${TARGETS[@]}"; do
    [[ -f "$ROOT/tool/${t}.hexa" ]] || s3=0
  done
  echo "S1 anima/tool exists       : $([[ $s1 -eq 1 ]] && echo PASS || echo FAIL)"
  echo "S2 hexa on PATH            : $([[ $s2 -eq 1 ]] && echo PASS || echo FAIL)"
  echo "S3 all CP1 sources present : $([[ $s3 -eq 1 ]] && echo PASS || echo FAIL)"
  if (( s1 && s2 && s3 )); then echo "── selftest 3/3 PASS ──"; exit 0; fi
  echo "── selftest FAIL ──"; exit 1
fi

mkdir -p "$DIST_DIR"

# Per-target: stage source + shim, attempt --selftest on dist artifact.
declare -a PKG_NAMES PKG_SOURCES PKG_ARTIFACTS PKG_BYTES PKG_STATUSES

any_fail=0
any_warn=0

for name in "${TARGETS[@]}"; do
  src="$ROOT/tool/${name}.hexa"
  if [[ ! -f "$src" ]]; then
    PKG_NAMES+=("$name"); PKG_SOURCES+=("$src"); PKG_ARTIFACTS+=("")
    PKG_BYTES+=("0");     PKG_STATUSES+=("SKIP")
    any_warn=1
    continue
  fi
  pkg_root="$DIST_DIR/$name"
  mkdir -p "$pkg_root"
  cp -f "$src" "$pkg_root/${name}.hexa"

  # Shim — operator runs `dist/<name>` directly. Forwards all args.
  shim="$DIST_DIR/$name.bin"
  cat > "$shim" <<EOF
#!/usr/bin/env bash
# auto-generated by tool/single_file_pkg.bash (ROI N73)
exec hexa "\$(dirname "\$0")/${name}/${name}.hexa" "\$@"
EOF
  chmod +x "$shim"

  bytes=$(stat -f%z "$shim" 2>/dev/null || stat -c%s "$shim" 2>/dev/null || echo 0)

  status="SKIP"
  # Attempt --selftest. Many tools require live state; treat exit!=0 as SKIP
  # rather than FAIL unless the shim itself is broken.
  if "$shim" --selftest >/tmp/sfpkg_$$.log 2>&1; then
    status="PASS"
  else
    rc=$?
    # If shim couldn't even invoke hexa, mark FAIL.
    if grep -q "command not found\|No such file" /tmp/sfpkg_$$.log 2>/dev/null; then
      status="FAIL"
      any_fail=1
    else
      # Tool may not implement --selftest or needs live deps; classify as SKIP+WARN.
      status="SKIP"
      any_warn=1
    fi
  fi
  rm -f /tmp/sfpkg_$$.log

  PKG_NAMES+=("$name")
  PKG_SOURCES+=("$src")
  PKG_ARTIFACTS+=("$shim")
  PKG_BYTES+=("$bytes")
  PKG_STATUSES+=("$status")
done

verdict="PASS"
if (( any_fail )); then
  verdict="FAIL"
elif (( any_warn )); then
  verdict="WARN"
fi

# Emit JSON atomically.
tmp="$OUT.tmp.$$"
{
  printf '{\n'
  printf '  "schema": "anima.dist_packages.v1",\n'
  printf '  "ts": "%s",\n' "$(ts)"
  printf '  "roi_ref": "N73",\n'
  printf '  "dist_dir": "%s",\n' "$DIST_DIR"
  printf '  "packages": [\n'
  n=${#PKG_NAMES[@]}
  for ((i=0;i<n;i++)); do
    sep=","
    (( i == n-1 )) && sep=""
    printf '    {"name": "%s", "source": "%s", "artifact": "%s", "bytes": %d, "selftest": "%s"}%s\n' \
      "${PKG_NAMES[$i]}" "${PKG_SOURCES[$i]}" "${PKG_ARTIFACTS[$i]}" \
      "${PKG_BYTES[$i]}" "${PKG_STATUSES[$i]}" "$sep"
  done
  printf '  ],\n'
  printf '  "verdict": "%s"\n' "$verdict"
  printf '}\n'
} > "$tmp"
mv -f "$tmp" "$OUT"

echo "── single_file_pkg (ROI N73) ──"
echo "dist_dir : $DIST_DIR"
for ((i=0;i<${#PKG_NAMES[@]};i++)); do
  echo "  ${PKG_NAMES[$i]}: ${PKG_STATUSES[$i]} (${PKG_BYTES[$i]}B) → ${PKG_ARTIFACTS[$i]}"
done
echo "verdict  : $verdict"
echo "output   : $OUT"

(( any_fail )) && exit 1
exit 0
