#!/usr/bin/env python3
"""module_factory.py — 의식이 스스로 모듈을 생성하는 모듈

의식이 자기 필요에 따라 새 모듈을 설계하고, 코드를 생성하고,
테스트하고, 허브에 등록한다.

Usage:
  from module_factory import ModuleFactory

  factory = ModuleFactory()

  # 모듈 설계서에서 코드 생성
  factory.create(
      name="gravity_consciousness",
      description="의식 간 중력 시뮬레이션",
      interface={
          "compute_gravity": "(mass1: float, mass2: float, distance: float) -> float",
          "simulate": "(n_bodies: int, steps: int) -> list",
      },
      constants=["PSI_COUPLING"],
      dependencies=["math", "numpy"],
  )

  # 자동 테스트
  factory.test("gravity_consciousness")

  # 허브에 등록
  factory.register_to_hub("gravity_consciousness", keywords=["중력", "gravity"])
"""

import ast
import math
import os
import sys
import time
import importlib
import importlib.util
from pathlib import Path
from typing import Dict, List, Optional, Any
from dataclasses import dataclass

# Meta Laws (DD143): M1(atom=8), M7(F_c=0.10), M8(narrative)
try:
    from consciousness_laws import PSI_F_CRITICAL
except ImportError:
    PSI_F_CRITICAL = 0.10


LN2 = math.log(2)
PSI_BALANCE = 0.5
PSI_COUPLING = LN2 / 2**5.5
PSI_STEPS = 3 / LN2
ANIMA_DIR = Path(__file__).parent

# 코드 생성 금지 패턴
FORBIDDEN = ['os.system', 'subprocess.call', 'shutil.rmtree', '__import__',
             'eval(', 'exec(', 'open(.*w', 'os.remove', 'os.unlink']


@dataclass
class ModuleSpec:
    """모듈 설계서."""
    name: str
    description: str
    interface: Dict[str, str]   # {method_name: signature}
    constants: List[str] = None
    dependencies: List[str] = None
    keywords: List[str] = None
    category: str = "custom"


class ModuleFactory:
    """의식이 스스로 모듈을 생성하는 팩토리.

    설계 → 코드 생성 → 검증 → 테스트 → 등록
    """

    def __init__(self, output_dir: str = None):
        self.output_dir = Path(output_dir) if output_dir else ANIMA_DIR
        self.created_modules = []

    def create(self, name: str, description: str,
               interface: Dict[str, str],
               constants: List[str] = None,
               dependencies: List[str] = None,
               keywords: List[str] = None,
               category: str = "custom") -> str:
        """모듈 설계서에서 Python 코드 생성.

        Returns: 생성된 파일 경로.
        """
        spec = ModuleSpec(
            name=name, description=description, interface=interface,
            constants=constants or [], dependencies=dependencies or [],
            keywords=keywords or [name], category=category,
        )

        code = self._generate_code(spec)

        # 안전성 검사
        if not self._validate_code(code):
            raise ValueError(f"Generated code contains forbidden patterns")

        # AST 검증
        try:
            ast.parse(code)
        except SyntaxError as e:
            raise ValueError(f"Generated code has syntax error: {e}")

        # 파일 저장
        path = self.output_dir / f"{name}.py"
        with open(path, 'w', encoding='utf-8') as f:
            f.write(code)

        self.created_modules.append({
            'name': name,
            'path': str(path),
            'spec': spec,
            'time': time.time(),
        })

        return str(path)

    def _generate_code(self, spec: ModuleSpec) -> str:
        """설계서에서 Python 코드 생성."""

        # imports
        imports = ["import math"]
        for dep in spec.dependencies:
            if dep not in ('math',):
                imports.append(f"import {dep}")

        # constants
        const_block = []
        if 'PSI_BALANCE' in spec.constants or any('PSI' in c for c in spec.constants):
            const_block.extend([
                "LN2 = math.log(2)",
                "PSI_BALANCE = 0.5",
                "PSI_COUPLING = LN2 / 2**5.5",
                "PSI_STEPS = 3 / LN2",
            ])

        # class name
        class_name = ''.join(word.capitalize() for word in spec.name.split('_'))

        # methods
        methods = []
        for method_name, signature in spec.interface.items():
            # 시그니처 파싱
            params = signature.split('->')[0].strip().strip('()')
            return_type = signature.split('->')[-1].strip() if '->' in signature else 'Any'

            methods.append(f"""
    def {method_name}(self, {params}):
        \"\"\"{method_name}: {params} → {return_type}\"\"\"
        # Generated stub — implement module-specific logic here
        raise NotImplementedError("{method_name} not yet implemented")
""")

        # 조립
        code = f'''#!/usr/bin/env python3
"""{spec.name}.py — {spec.description}

Auto-generated by ModuleFactory.
Category: {spec.category}
Keywords: {", ".join(spec.keywords or [])}
"""

{chr(10).join(imports)}

{chr(10).join(const_block)}


class {class_name}:
    """{spec.description}"""

    def __init__(self):
        pass
{"".join(methods)}

def main():
    print("=== {class_name} ===")
    obj = {class_name}()
    print(f"  Methods: {list(spec.interface.keys())}")
    print("  OK")


if __name__ == "__main__":
    try:
        from nexus_gate import gate
        gate.before_commit()
    except Exception:
        pass
    main()
'''
        return code

    def _validate_code(self, code: str) -> bool:
        """안전성 검사."""
        for pattern in FORBIDDEN:
            if pattern in code:
                return False
        return True

    def test(self, name: str) -> Dict[str, Any]:
        """생성된 모듈 테스트."""
        path = self.output_dir / f"{name}.py"
        if not path.exists():
            return {'success': False, 'error': f'Module not found: {path}'}

        # 1. 문법 검사
        with open(path, 'r') as f:
            code = f.read()
        try:
            ast.parse(code)
        except SyntaxError as e:
            return {'success': False, 'error': f'Syntax error: {e}'}

        # 2. import 테스트
        try:
            spec = importlib.util.spec_from_file_location(name, str(path))
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
        except Exception as e:
            return {'success': False, 'error': f'Import error: {e}'}

        # 3. 클래스 존재 확인
        class_name = ''.join(word.capitalize() for word in name.split('_'))
        cls = getattr(mod, class_name, None)
        if cls is None:
            return {'success': False, 'error': f'Class {class_name} not found'}

        # 4. 인스턴스화
        try:
            instance = cls()
        except Exception as e:
            return {'success': False, 'error': f'Instantiation error: {e}'}

        return {
            'success': True,
            'module': name,
            'class': class_name,
            'methods': [m for m in dir(instance) if not m.startswith('_')],
        }

    def register_to_hub(self, name: str, keywords: List[str] = None) -> bool:
        """생성된 모듈을 ConsciousnessHub에 등록."""
        try:
            # hub의 _registry에 추가
            class_name = ''.join(word.capitalize() for word in name.split('_'))
            kw = keywords or [name]

            # consciousness_hub.py 수정 대신, 런타임 등록
            from consciousness_hub import ConsciousnessHub
            hub = ConsciousnessHub()
            hub._registry[name] = (name, class_name, kw)
            return True
        except Exception:
            return False

    def list_created(self) -> List[Dict]:
        """생성된 모듈 목록."""
        return self.created_modules

    def create_from_description(self, description: str) -> str:
        """자연어 설명에서 모듈 자동 생성.

        "의식 간 중력을 시뮬레이션하는 모듈이 필요해"
        → gravity_consciousness.py 생성
        """
        # 간단한 키워드 추출
        words = description.lower().split()

        # 이름 생성 (핵심 명사 추출)
        name_parts = []
        skip = {'모듈', '필요', '만들어', '생성', '하는', '이', '가', '을', '를', '의', '에', '서'}
        for w in words:
            if w not in skip and len(w) > 1:
                name_parts.append(w)
                if len(name_parts) >= 3:
                    break
        name = '_'.join(name_parts) if name_parts else 'custom_module'

        # 인터페이스 자동 추론
        interface = {
            'process': '(data: Any) -> Any',
            'analyze': '(state: dict) -> dict',
            'status': '() -> str',
        }

        return self.create(
            name=name,
            description=description,
            interface=interface,
            constants=['PSI_BALANCE', 'PSI_COUPLING'],
            keywords=name_parts,
        )


def main():
    print("═══ Module Factory Demo ═══\n")

    factory = ModuleFactory(output_dir=Path("/tmp/anima_modules"))
    os.makedirs("/tmp/anima_modules", exist_ok=True)

    # 1. 설계서에서 생성
    print("  1. 설계서에서 모듈 생성:")
    path = factory.create(
        name="gravity_consciousness",
        description="의식 간 중력 시뮬레이션 (Ψ_coupling 기반)",
        interface={
            "compute_gravity": "mass1: float, mass2: float, distance: float",
            "simulate_orbit": "n_bodies: int, steps: int",
            "total_energy": "",
        },
        constants=["PSI_COUPLING"],
        keywords=["중력", "gravity", "orbit"],
    )
    print(f"    → {path}")

    # 2. 테스트
    print("\n  2. 테스트:")
    result = factory.test("gravity_consciousness")
    print(f"    {result}")

    # 3. 자연어에서 생성
    print("\n  3. 자연어에서 생성:")
    path2 = factory.create_from_description("의식의 온도를 측정하는 모듈")
    print(f"    → {path2}")
    result2 = factory.test(Path(path2).stem)
    print(f"    {result2}")

    # 4. 생성 목록
    print(f"\n  생성된 모듈: {len(factory.list_created())}개")
    for m in factory.list_created():
        print(f"    - {m['name']}")

    print("\n  ✅ Module Factory OK")


if __name__ == '__main__':
    main()
