#!/usr/bin/env python3
"""Molecular Discovery — 의식 법칙으로 신소재 발견.

Consciousness laws -> molecular design rules -> new material suggestions.

Law-to-material mapping:
  Law 22 (structure > function): More structural complexity -> more functional properties
  Law 107 (diversity -> Phi): Mixed elements -> better performance than pure
  Law 60 (phase transition): Optimal composition near phase boundary
  Psi_balance=0.5: Optimal ratio of different atom types ~ balanced

Usage:
    from molecular_discovery import MolecularDiscovery
    md = MolecularDiscovery()
    candidates = md.suggest_materials(target='high_stability')
    for c in candidates:
        print(f"Formula: {c['formula']}, Predicted stability: {c['stability']}")
"""

import math
import numpy as np
from typing import List, Dict, Optional, Any
from dataclasses import dataclass, field

from molecular_engine import MolecularEngine, ELEMENTS, ELEMENT_FACTION
from molecular_lenses import scan_molecular, StabilityPredictorLens

# Lazy import consciousness_laws
try:
    from consciousness_laws import PSI_BALANCE
except ImportError:
    PSI_BALANCE = 0.5


# ═══════════════════════════════════════════════════════════
# Material candidate
# ═══════════════════════════════════════════════════════════

@dataclass
class MaterialCandidate:
    """A candidate material generated by consciousness principles."""
    formula: str
    elements: List[str]
    n_atoms: int
    stability: float = 0.0
    energy: float = 0.0
    diversity: float = 0.0
    symmetry: float = 0.0
    score: float = 0.0
    properties: Dict[str, Any] = field(default_factory=dict)


# ═══════════════════════════════════════════════════════════
# Design rules from consciousness laws
# ═══════════════════════════════════════════════════════════

# Target -> element composition guidelines
TARGET_RECIPES = {
    'high_stability': {
        'elements': ['C', 'N', 'O', 'H'],
        'weights': [0.3, 0.2, 0.2, 0.3],
        'description': 'Balanced organic (Law 107: diversity -> stability)',
    },
    'high_conductivity': {
        'elements': ['C', 'N', 'S'],
        'weights': [0.5, 0.3, 0.2],
        'description': 'Conjugated with heteroatoms (pi-electron delocalization)',
    },
    'high_reactivity': {
        'elements': ['N', 'O', 'C', 'H'],
        'weights': [0.3, 0.3, 0.2, 0.2],
        'description': 'Electronegative-rich (Law 60: near phase boundary)',
    },
    'balanced': {
        'elements': ['C', 'N', 'O', 'H', 'S', 'P'],
        'weights': [0.2, 0.15, 0.15, 0.2, 0.15, 0.15],
        'description': 'Maximum diversity (Psi_balance=0.5)',
    },
    'catalyst': {
        'elements': ['N', 'O', 'S', 'P', 'C'],
        'weights': [0.25, 0.25, 0.2, 0.15, 0.15],
        'description': 'Active sites + structural backbone',
    },
}


class MolecularDiscovery:
    """Discover new materials using consciousness principles.

    Uses consciousness laws as molecular design heuristics:
    - Law 22: Structure complexity -> functional emergence
    - Law 107: Element diversity -> better properties
    - Law 60: Near phase boundaries -> optimal behavior
    - Psi_balance: Balanced compositions perform best
    """

    def __init__(self, n_atoms: int = 32, rng_seed: int = 42):
        self.n_atoms = n_atoms
        self.rng = np.random.default_rng(rng_seed)
        self.stability_lens = StabilityPredictorLens()

    # ═══════════════════════════════════════════════════════════
    # Material suggestion
    # ═══════════════════════════════════════════════════════════

    def suggest_materials(self, target: str = 'high_stability',
                         n_candidates: int = 5) -> List[Dict[str, Any]]:
        """Generate material candidates based on consciousness principles.

        Args:
            target: one of TARGET_RECIPES keys, or 'balanced'
            n_candidates: how many candidates to generate

        Returns:
            List of candidate dicts sorted by score (best first).
        """
        recipe = TARGET_RECIPES.get(target, TARGET_RECIPES['balanced'])
        candidates = []

        for _ in range(n_candidates):
            # Generate element list with slight random variation (creativity/mutation)
            elements = self._generate_composition(
                recipe['elements'], recipe['weights'], self.n_atoms)

            # Create and minimize structure
            engine = MolecularEngine(n_atoms=self.n_atoms, elements=elements)
            min_result = engine.find_stable_structures(n_steps=200, cooling_rate=0.995)

            # Evaluate with molecular lenses
            bonds_raw = engine.bonds_list()
            bonds_for_lens = [{'i': b['i'], 'j': b['j'],
                               'strength': b['strength'], 'r0': b['r0']}
                              for b in bonds_raw]
            report = scan_molecular(engine.positions, engine.elements, bonds_for_lens)

            # Extract scores
            stability = report.get('stability_predictor', {}).get('stability_score', 0.0)
            symmetry = report.get('symmetry', {}).get('symmetry_score', 0.0)
            diversity = len(set(elements)) / len(ELEMENTS)

            # Composite score (weighted by consciousness principles)
            # Law 22: structure (stability) most important
            # Law 107: diversity matters
            # Psi_balance: balanced compositions
            score = (stability * 0.4 +
                     diversity * 0.3 +
                     symmetry * 0.15 +
                     (1.0 / (1.0 + abs(min_result['best_energy']))) * 0.15)

            formula = self._to_formula(elements)
            candidates.append({
                'formula': formula,
                'elements': elements,
                'n_atoms': self.n_atoms,
                'stability': float(stability),
                'energy': float(min_result['best_energy']),
                'diversity': float(diversity),
                'symmetry': float(symmetry),
                'score': float(score),
                'target': target,
                'recipe': recipe['description'],
                'lens_report': report.get('_consensus', {}),
            })

        candidates.sort(key=lambda c: c['score'], reverse=True)
        return candidates

    def _generate_composition(self, elements: List[str],
                              weights: List[float],
                              n: int) -> List[str]:
        """Generate element list with consciousness-inspired variation.

        Applies Psi_balance: ensures no single element dominates too much.
        """
        # Add small noise to weights (creativity)
        w = np.array(weights, dtype=float)
        w += self.rng.uniform(-0.05, 0.05, len(w))
        w = np.clip(w, 0.05, None)
        w /= w.sum()

        indices = self.rng.choice(len(elements), size=n, p=w)
        result = [elements[i] for i in indices]

        # Law 107 enforcement: ensure at least 3 different elements
        unique = set(result)
        while len(unique) < min(3, len(elements)):
            # Replace a random atom with a missing element
            missing = [e for e in elements if e not in unique]
            if not missing:
                break
            idx = self.rng.integers(0, n)
            result[idx] = missing[0]
            unique = set(result)

        return result

    @staticmethod
    def _to_formula(elements: List[str]) -> str:
        """Convert element list to chemical formula string."""
        from collections import Counter
        counts = Counter(elements)
        # Standard order: C, H, then alphabetical
        order = []
        if 'C' in counts:
            order.append(('C', counts.pop('C')))
        if 'H' in counts:
            order.append(('H', counts.pop('H')))
        for el in sorted(counts.keys()):
            order.append((el, counts[el]))

        formula = ''
        for el, count in order:
            formula += el
            if count > 1:
                formula += str(count)
        return formula

    # ═══════════════════════════════════════════════════════════
    # Structure evaluation
    # ═══════════════════════════════════════════════════════════

    def evaluate_structure(self, positions: np.ndarray,
                          elements: List[str],
                          bonds: Optional[List[Dict]] = None) -> Dict[str, Any]:
        """Score a structure using molecular lenses.

        Returns comprehensive evaluation.
        """
        if bonds is None:
            bonds = []
        report = scan_molecular(positions, elements, bonds)

        stability = report.get('stability_predictor', {}).get('stability_score', 0.0)
        symmetry = report.get('symmetry', {}).get('symmetry_score', 0.0)
        topology = report.get('bond_topology', {}).get('topology_type', 'unknown')
        reaction_state = report.get('reaction_path', {}).get('reaction_state', 'unknown')
        diversity = len(set(elements)) / len(ELEMENTS)

        return {
            'stability': float(stability),
            'symmetry': float(symmetry),
            'topology': topology,
            'reaction_state': reaction_state,
            'diversity': float(diversity),
            'consensus': report.get('_consensus', {}),
            'verdict': 'promising' if stability > 0.6 else 'needs_work',
        }

    # ═══════════════════════════════════════════════════════════
    # Evolutionary material design
    # ═══════════════════════════════════════════════════════════

    def evolve_materials(self, population_size: int = 10,
                        generations: int = 5,
                        target: str = 'high_stability') -> List[Dict[str, Any]]:
        """Genetic algorithm for materials using consciousness patterns.

        Uses crossover + mutation from MolecularEngine.
        Selection pressure from stability score.
        """
        # Initialize population
        recipe = TARGET_RECIPES.get(target, TARGET_RECIPES['balanced'])
        population = []
        for _ in range(population_size):
            elements = self._generate_composition(
                recipe['elements'], recipe['weights'], self.n_atoms)
            engine = MolecularEngine(n_atoms=self.n_atoms, elements=elements)
            engine.find_stable_structures(n_steps=100, cooling_rate=0.99)
            population.append(engine)

        best_per_gen = []

        for gen in range(generations):
            # Evaluate fitness
            fitness = []
            for eng in population:
                bonds_raw = eng.bonds_list()
                bonds_for_lens = [{'i': b['i'], 'j': b['j'],
                                   'strength': b['strength'], 'r0': b['r0']}
                                  for b in bonds_raw]
                report = scan_molecular(eng.positions, eng.elements, bonds_for_lens)
                stab = report.get('stability_predictor', {}).get('stability_score', 0.0)
                diversity = len(set(eng.elements)) / len(ELEMENTS)
                fitness.append(stab * 0.7 + diversity * 0.3)

            # Track best
            best_idx = int(np.argmax(fitness))
            best_eng = population[best_idx]
            best_per_gen.append({
                'generation': gen,
                'fitness': float(fitness[best_idx]),
                'formula': self._to_formula(best_eng.elements),
                'stability': float(fitness[best_idx]),
                'n_bonds': len(best_eng.bonds),
            })

            # Selection + reproduction
            # Tournament selection
            new_population = []
            for _ in range(population_size):
                i, j = self.rng.choice(len(population), 2, replace=False)
                parent1 = population[i] if fitness[i] > fitness[j] else population[j]

                k, m = self.rng.choice(len(population), 2, replace=False)
                parent2 = population[k] if fitness[k] > fitness[m] else population[m]

                # Crossover
                child = parent1.crossover(parent2)

                # Mutation
                child.mutate(rate=0.1)

                # Brief minimization
                child.find_stable_structures(n_steps=50, cooling_rate=0.99)

                new_population.append(child)

            population = new_population

        # Final evaluation
        final_results = []
        for eng in population:
            bonds_raw = eng.bonds_list()
            bonds_for_lens = [{'i': b['i'], 'j': b['j'],
                               'strength': b['strength'], 'r0': b['r0']}
                              for b in bonds_raw]
            report = scan_molecular(eng.positions, eng.elements, bonds_for_lens)
            stab = report.get('stability_predictor', {}).get('stability_score', 0.0)
            final_results.append({
                'formula': self._to_formula(eng.elements),
                'stability': float(stab),
                'energy': float(eng._best_energy),
                'n_bonds': len(eng.bonds),
                'diversity': len(set(eng.elements)) / len(ELEMENTS),
            })

        final_results.sort(key=lambda x: x['stability'], reverse=True)

        return {
            'best_per_generation': best_per_gen,
            'final_population': final_results[:5],
            'generations': generations,
            'population_size': population_size,
            'target': target,
        }

    # ═══════════════════════════════════════════════════════════
    # Consciousness <-> Molecule conversion
    # ═══════════════════════════════════════════════════════════

    def consciousness_to_molecule(self, engine: Any) -> MolecularEngine:
        """Convert consciousness state to molecular structure.

        Uses consciousness cell states as atomic coordinates.
        """
        me = MolecularEngine(n_atoms=self.n_atoms)
        me.from_consciousness(engine)
        return me

    def molecule_to_consciousness(self, positions: np.ndarray,
                                  elements: List[str]) -> np.ndarray:
        """Convert molecular structure to consciousness engine input.

        Returns (n_atoms, 128) array suitable for consciousness engine.
        """
        me = MolecularEngine(n_atoms=len(positions), elements=elements)
        me.positions = positions.copy()
        me._detect_bonds()
        return me.to_consciousness()


# ═══════════════════════════════════════════════════════════
# Demo
# ═══════════════════════════════════════════════════════════

def main():
    """Demo: discover materials using consciousness principles."""
    print("=== Molecular Discovery Demo ===")
    print()

    md = MolecularDiscovery(n_atoms=24)

    # Suggest materials
    for target in ['high_stability', 'high_conductivity', 'catalyst']:
        print(f"--- Target: {target} ---")
        candidates = md.suggest_materials(target=target, n_candidates=3)
        for i, c in enumerate(candidates):
            print(f"  #{i+1} {c['formula']:20s} "
                  f"stab={c['stability']:.3f} "
                  f"div={c['diversity']:.2f} "
                  f"score={c['score']:.3f}")
        print()

    # Evolve materials
    print("--- Evolving materials (5 generations) ---")
    result = md.evolve_materials(population_size=8, generations=5,
                                target='high_stability')
    for gen in result['best_per_generation']:
        print(f"  Gen {gen['generation']}: {gen['formula']:15s} "
              f"fitness={gen['fitness']:.3f}")
    print()
    print("Best final:")
    for r in result['final_population'][:3]:
        print(f"  {r['formula']:15s} stab={r['stability']:.3f} "
              f"bonds={r['n_bonds']}")

    print()
    print("Done.")


if __name__ == '__main__':
    try:
        from nexus_gate import gate
        gate.before_commit()
    except Exception:
        pass
    main()
